export {candidateFormObj,joinedCoursesObj} from './candidate'
export {batchObj} from './masters'
export {userObj} from './user'
export {attendanceFormObject} from './attendance'
export {accountsFormObj} from './accounts'
