export {MENU} from './menu'
export {DB_NAME,WEEK_LIST,ALL_BG_PLACEHOLDERS,USER_ROLE,USER_TYPE,ATTENDANCE,EXIST_LOCAL_STORAGE,CONFIG,CANDIDATE_COURSE_STATUS,INSTITUTE_BRANCH,COURSE_LIST,CLASS_TYPE,CURRENT_USER,STATUS,YES_NO,COURSE_TRAINER} from './app'
